version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: go-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: vue-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always